# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46371f8c23248a42b668b44d586fe2bcbe2ce1dfdf98ef891f00fef0bf6b2e383613cab4028644e1283d4baeeda00bb033dbe3245b934140e669611864b023fe

test:
  secret_key_base: fdf087bf4dde4cfeb2bf362580ecf1c4bbb196f52a77c8e5963a9898780645599817f1f737407937c043ac99747324830e7b4e2cf3b3e225d98b1382fb94c4a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
